version: '3'

services:
  pg:
    container_name: pg-cli
    restart: 'no'
    image: jbergknoff/postgresql-client
    # add a link so we can use our SSL domain
    links:
      - 'postgres:${PG_DOMAIN}'
