version: "3"

services:
  mariadb-backup:
    image: fradelg/mysql-cron-backup
    networks:
      - dbs
    depends_on:
      - mariadb
    volumes:
      - ./data/backup/mariadb:/backup
    environment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=root
      - MYSQL_PASS=${MARIADB_ROOT_PASSWORD}
      - MAX_BACKUPS=7
      - INIT_BACKUP=1
      - CRON_TIME=0 0 * * *
    restart: unless-stopped
