version: '3'

services:
  pg-backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./data/pg-backups:/backups
    links:
      - db
    depends_on:
      - db
    networks:
      - dbs
    environment:
      POSTGRES_HOST: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_EXTRA_OPTS: -Z6 --schema=public --blobs
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 3
      BACKUP_KEEP_WEEKS: 2
      BACKUP_KEEP_MONTHS: 2
