version: "3"

services:
  postgres:
    restart: "always"
    image: postgres:11-bullseye
    environment:
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432
    depends_on:
      - certbot-pg
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./pg/pg.d/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      #- ./pg.d/hba.sh:/docker-entrypoint-initdb.d/hba.sh
      - certbot_pg:/etc/postgresql/certificates
  certbot-pg:
    restart: "no"
    image: certbot/dns-cloudflare
    volumes:
      - certbot_pg:/etc/letsencrypt
      - ./.cloudflare.ini:/root/cloudflare.ini
      - ./pg/certbot/chown_pg.sh/:/usr/local/bin/pg_chown.sh
    command: >-
      certonly --dns-cloudflare
      --non-interactive
      --keep-until-expiring
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email ssl@kontextwork.de
      --agree-tos --no-eff-email
      -d pg.kontextwork.in 
      --post-hook /usr/local/bin/pg_chown.sh
volumes:
  certbot_pg:
  pg_data: