version: '3'

services:
  mysql:
    container_name: my
    restart: always
    image: mariadb:10.3
    depends_on:
      - certbot-mysql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql_certificates:/etc/mysql/certificates
  certbot-mysql:
    restart: no
    image: certbot/dns-cloudflare
    volumes:
      - ./data/certbot_mysql:/etc/letsencrypt
      - ./data/mysql_certificates:/mysql_certificates
      - ./mysql/certbot/deploy_mysql.sh:/usr/local/bin/deploy_mysql.sh
    command: >-
      certonly --dns-cloudflare
      --non-interactive
      --keep-until-expiring
      --dns-cloudflare-credentials /root/cloudflare.ini
      --dns-cloudflare-propagation-seconds 15
      --email ssl@kontextwork.de
      --agree-tos --no-eff-email
      -d ${MYSQL_DOMAIN}
      --deploy-hook /usr/local/bin/deploy_mysql.sh
    configs:
      - source: cloudflare
        target: /root/cloudflare.ini
        mode: 0440
volumes:
  certbot_mysql:
  mysql_data:
